add frontend challenge
woovibr/awesome-woovi-challenge pull request #41
Opened 2024-07-20 13:41 UTC by gaia-j

2024-07-23 18:30 UTC, daniloab commented
fix conflicts

2024-08-06 18:12 UTC, daniloab requested changes, later dismissed
fix readme

2024-08-06 19:23 UTC, edumaciel10 approved these changes

2025-05-07 12:08 UTC, iagxferreira approved these changes
lgtm!

2025-05-07 12:08 UTC, merged